"""Application configuration, sourced from environment variables (.env)."""
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")

    database_url: str = "sqlite:///./fireflies.db"
    cors_origins: str = "http://localhost:3000"
    environment: str = "development"
    # Optional. When set, meeting summaries are generated by calling Claude
    # instead of the built-in heuristic — see app/services/ai_summary.py.
    anthropic_api_key: str = ""

    @property
    def cors_origins_list(self) -> list[str]:
        return [origin.strip() for origin in self.cors_origins.split(",") if origin.strip()]


settings = Settings()
